apiVersion: batch/v1
kind: Job
metadata:
  name: db-maniskill-job-xarm6
spec:
  template:
    spec:
      containers:
      - name: gpu-container
        image: dhbhatt/maniskill-experiments:v4.1_tdmpc
        command: ["/bin/bash", "-c"]
        args: [
          # "export WANDB_API_KEY=ebf815cc1a406e10c78314a2a137fa38d83c0b02 && \
          # python examples/baselines/sac/sac.py \
          #        --wandb-entity ucsd_erl --wandb-project-name maniskill_experiments \
          #        --exp_name PickCube_xarm6_allegro_left_joint_vel \
          #        --env-id PickCube-v1 \
          #        --robot xarm6_allegro_left \
          #        --control_mode pd_joint_vel \
          #        --num-envs 128 \
          #        --training-freq 128 \
          #        --num-eval-steps 100 \
          #        --total-timesteps 10000000 \
          #        --wandb-video-freq 1900000 \
          #        --track \
          #   > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-sac.log"

          # "export WANDB_API_KEY=ebf815cc1a406e10c78314a2a137fa38d83c0b02 && \
          # python examples/baselines/tdmpc2/train.py \
          #         model_size=5 \
          #         steps=5_000_000 \
          #         seed=1 \
          #         exp_name=PlaceCube_xarm6_pandagripper_joint_vel_tdmpc2 \
          #         env_id=PlaceCube-v1 \
          #         robot_uids=xarm6_pandagripper \
          #         control_mode=pd_joint_vel \
          #         env_type=gpu \
          #         num_envs=32 \
          #         obs=state \ 
          #         save_video_local=true \
          #         wandb=true \
          #     > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-tdmpc.log"

          "export WANDB_API_KEY=ebf815cc1a406e10c78314a2a137fa38d83c0b02 && \
          python examples/baselines/ppo/ppo.py \
                  --env_id=PlaceCube-v1 \
                  --robot_uids=xarm6_pandagripper \
                  --control_mode=pd_joint_vel \
                  --exp_name=PlaceCube_xarm6_pandagripper_jv_ppo \
                  --num_envs=512 \
                  --num_eval_envs=8 \
                  --eval_freq=10 \
                  --total_timesteps=10_000_000 \
                  --num_steps=50 \
                  --num_minibatches=32 \
                  --num_eval_steps=50 \
                  --gamma=0.8 \
                  --update_epochs=4 \
                  --track \
                  --wandb_video_freq=50 \
              > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-ppo.log"
        ]
        volumeMounts:
        - mountPath: /pers_vol
          name: db-cephfs-volume
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "156G"
            cpu: "32"
          requests:
            nvidia.com/gpu: "1"
            memory: "128G"
            cpu: "24"
      affinity:
        # nodeAffinity:
        # nodeSelectorTerms:
        # - matchExpressions:
        #   - key: nvidia.com/gpu.product
        #     operator: In
        #     values:
        #     - "NVIDIA-A100-80GB-PCIe"
        #     - "NVIDIA-A100-SXM4-80GB"      
        #     - "NVIDIA-GeForce-RTX-4090"
        #     - "NVIDIA-GeForce-RTX-3090"
        #     - "NVIDIA-A40"
        #     - "NVIDIA-A10"
        #     - "Tesla-V100-SXM2-32GB"
        #     - "NVIDIA_TITAN_RTX"
        #     - "NVIDIA-RTX-A6000"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - "NVIDIA-A100-80GB-PCIe"
                - "NVIDIA-A100-SXM4-80GB"      
                - "NVIDIA-GeForce-RTX-4090"
                - "NVIDIA-GeForce-RTX-3090"
          - weight: 15
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - "NVIDIA-A40"
                - "NVIDIA-A10"
                - "Tesla-V100-SXM2-32GB"
          - weight: 5
            preference:
              matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - "NVIDIA_TITAN_RTX"
                - "NVIDIA-RTX-A6000"
      restartPolicy: Never
      volumes:
        - name: db-cephfs-volume
          persistentVolumeClaim:
            claimName: db-cephfs-volume
