apiVersion: v1
kind: Pod
metadata:
  name: db-maniskill-td3-placecube
spec:
  containers:
  - name: gpu-container
    image: dhbhatt/maniskill-experiments:latest
    command: ["/bin/bash", "-c"]
    # args: [
    #   "jupyter lab --NotebookApp.token=627a7b3b --ip=0.0.0.0 --allow-root >> /pers_vol/dwait/jupyter.log 2>&1"
    # ]
    args: [
          # "git pull && \
          # echo y | python examples/baselines/sac/sac.py \
          #        --wandb-entity ucsd_erl --wandb-project-name maniskill_experiments \
          #        --env-id PickCube-v1 \
          #        --robot xarm6_robotiq \
          #        --control_mode pd_joint_vel \
          #        --exp_name PlaceCubeTuned_sac_xarm6_robotiq_jv \
          #        --num-envs 128 \
          #        --training-freq 128 \
          #        --num-eval-steps 100 \
          #        --eval-freq 50_000 \
          #        --total-timesteps 1_000_000 \
          #        --wandb-video-freq 2 \
          #        --wandb_reward_trajectories \
          #        --track \
          #   > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-sac.log"

          "git pull && \
          echo y | python examples/baselines/td3/td3.py \
                 --wandb-entity ucsd_erl --wandb-project-name maniskill_experiments \
                 --env-id PlaceCube-v1 \
                 --robot xarm6_robotiq \
                 --control_mode pd_joint_vel \
                 --num-envs 128 \
                 --training-freq 128 \
                 --num-eval-steps 100 \
                 --eval-freq 50_000 \
                 --total-timesteps 1_000_000 \
                 --wandb-video-freq 2 \
                 --wandb_reward_trajectories \
                 --track \
            > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-td3.log"

          # "git pull && \
          # echo y | python examples/baselines/ppo/ppo.py \
          #         --env_id=PlaceCube-v1 \
          #         --robot_uids=xarm6_robotiq \
          #         --control_mode=pd_joint_vel \
          #         --num_envs=512 \
          #         --num_eval_envs=8 \
          #         --eval_freq=10 \
          #         --total_timesteps=200_000_000 \
          #         --num_steps=50 \
          #         --num_minibatches=32 \
          #         --num_eval_steps=50 \
          #         --gamma=0.8 \
          #         --update_epochs=4 \
          #         --track \
          #         --wandb_video_freq=2 \
          #     > /pers_vol/dwait/logs/$(date +%Y-%m-%d_%H-%M-%S)-ppo.log"
        ]
    env:
    - name: WANDB_API_KEY
      valueFrom:
        secretKeyRef:
          name: wandb-secret
          key: api-key
    volumeMounts:
    - mountPath: /pers_vol
      name: db-cephfs-volume
    resources:
      limits:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "16"
      requests:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "12"
  restartPolicy: Never
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nvidia.com/gpu.product
  #           operator: In
  #           values:
  #           - RTX-3090
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      # Empirically determined nodes with good network to download large docker images
      - weight: 100
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "ry-gpu-01.sdsc.optiputer.net"
            - "ry-gpu-02.sdsc.optiputer.net"
            - "ry-gpu-03.sdsc.optiputer.net"
            - "ry-gpu-04.sdsc.optiputer.net"
            - "ry-gpu-05.sdsc.optiputer.net"
            - "ry-gpu-06.sdsc.optiputer.net"
            - "ry-gpu-07.sdsc.optiputer.net"
            - "ry-gpu-08.sdsc.optiputer.net"
            - "ry-gpu-09.sdsc.optiputer.net"
            - "ry-gpu-10.sdsc.optiputer.net"
            - "ry-gpu-11.sdsc.optiputer.net"
            - "ry-gpu-12.sdsc.optiputer.net"
            - "ry-gpu-13.sdsc.optiputer.net"
            - "ry-gpu-14.sdsc.optiputer.net"
            - "ry-gpu-15.sdsc.optiputer.net"
            - "ry-gpu-16.sdsc.optiputer.net"
            - "k8s-3090-01.calit2.optiputer.net"
            - "k8s-4090-01.calit2.optiputer.net"
            - "k8s-4090-02.calit2.optiputer.net"
            - "k8s-haosu-02.sdsc.optiputer.net"
            - "k8s-haosu-03.sdsc.optiputer.net"
            - "k8s-haosu-04.sdsc.optiputer.net"
            - "k8s-haosu-05.sdsc.optiputer.net"
            - "k8s-haosu-06.sdsc.optiputer.net"
            - "k8s-haosu-07.sdsc.optiputer.net"
            - "k8s-haosu-08.sdsc.optiputer.net"
            - "k8s-haosu-09.sdsc.optiputer.net"
            - "k8s-haosu-10.sdsc.optiputer.net"
            - "k8s-haosu-11.sdsc.optiputer.net"
            - "k8s-haosu-12.sdsc.optiputer.net"
            - "k8s-haosu-13.sdsc.optiputer.net"
            - "k8s-haosu-14.sdsc.optiputer.net"
            - "k8s-haosu-15.sdsc.optiputer.net"
            - "k8s-haosu-16.sdsc.optiputer.net"
            - "k8s-haosu-17.sdsc.optiputer.net"
            - "k8s-haosu-18.sdsc.optiputer.net"
            - "k8s-haosu-19.sdsc.optiputer.net"
            - "k8s-haosu-20.sdsc.optiputer.net"
            - "k8s-haosu-21.sdsc.optiputer.net"
            - "k8s-haosu-22.sdsc.optiputer.net"
            - "k8s-haosu-23.sdsc.optiputer.net"
            - "k8s-haosu-24.sdsc.optiputer.net"
            - "k8s-haosu-25.sdsc.optiputer.net"
            - "k8s-haosu-26.sdsc.optiputer.net"
            - "k8s-haosu-27.sdsc.optiputer.net"
            - "k8s-haosu-28.sdsc.optiputer.net"
            - "k8s-haosu-29.sdsc.optiputer.net"
      - weight: 80
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA-A100-80GB-PCIe"
            - "NVIDIA-A100-SXM4-80GB"      
            - "NVIDIA-GeForce-RTX-4090"
            - "NVIDIA-GeForce-RTX-3090"
      - weight: 15
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA-A40"
            - "NVIDIA-A10"
            - "Tesla-V100-SXM2-32GB"
      - weight: 5
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA_TITAN_RTX"
            - "NVIDIA-RTX-A6000"
  volumes:
    - name: db-cephfs-volume
      persistentVolumeClaim:
        claimName: db-cephfs-volume
